### ISSUE TITLE
RESTify the backend

### ISSUE THREAD

**Issue by giraugh** [csitsociety/stevent#114]
Hype ✨

**Comment by GRA0007** [comment]
Should we consider graphql? @giraugh

**Comment by giraugh** [comment]
OOh thats tempting but I think because we are just using the backend, rather than it being a public API that it would be more effort than its worth.

**Comment by giraugh** [comment]
I'm going to create a proper swagger schema but for now here are my suggested route changes.

```
createClubEvent           ->  POST    /event                     {createEvent}
createClubPage            ->  POST    /club                      {createClub}
deleteClubPage            ->  DELETE  /club                      {deleteClub}
deleteClubEvent           ->  DELETE  /event                     {delteEvent}
retrieveAttendees         ->  GET     /event/:eventid/attendees  {getEventAttendees}
retrieveClubMembers       ->  GET     /club/:clubid/members      {getClubMembers}
retrieveClubDetails       ->  GET     /club                      {getClub}
retrieveDSUser            ->  GET     /user/:userid              {getUser}
retrieveEventDetails      ->  GET     /event/:eventid            {getEvent}
retrieveEventsFeed        ->  GET     /event                     {getAllEvents}
signUp                    ->  POST    /user                      {createUser}
updateAttendingEvent      ->  PUT     /user/events/:eventid      {updateUserEvents}
updateSubscriptionToClub  ->  PUT     /user/clubs/:clubid        {updateUserClubs}
updateUserImage           ->  PUT     /user/:userid/image        {updateUserImage}
updateUserInfo            ->  PUT     /user/:userid              {updateUser}
```

**Comment by giraugh** [comment]
Oh yeah, I'm doing this before #63 so I don't end up redoing it.

**Comment by GRA0007** [comment]
That looks pretty good, these are my suggested changes:

previousRouteName | -> | newRouteMethod | newRouteAddr | newRouteName
-|-|-|-|-
createClubEvent | -> | POST | /event | {createEvent}
createClubPage | -> | POST | /club | {createClub}
deleteClubPage | -> | DELETE | **/club/:clubid** | {deleteClub}
deleteClubEvent | -> | DELETE | **/event/:eventid** | {deleteEvent}
retrieveAttendees | -> | GET | /event/:eventid/attendees | {getEventAttendees}
retrieveClubMembers | -> | GET | /club/:clubid/members | {getClubMembers}
retrieveClubDetails | -> | GET | /club | {getClub}
retrieveDSUser | -> | GET | /user/:userid | {getUser}
retrieveEventDetails | -> | GET | /event/:eventid | {getEvent}
retrieveEventsFeed | -> | GET | /event | {getAllEvents}
signUp | -> | POST | /user | {createUser}
updateAttendingEvent | -> | PUT | /user/events/:eventid | {updateUserEvents}
updateSubscriptionToClub | -> | PUT | /user/clubs/:clubid | {updateUserClubs}
updateUserImage | -> | PUT | /user/:userid/image | {updateUserImage}
updateUserInfo | -> | PUT | /user/:userid | {updateUser}
? | -> | POST | /event/:eventid/notify | {notifyEventAttendees}

**Comment by giraugh** [comment]
ah yeah rip I missed those ids 👍 
(ooh a fancy actual table XD)

**Comment by giraugh** [comment]
Fixed some stuff
```
previousRouteName         ->  newRouteMethod  newRouteAddr               newRouteName
---------------------------------------------------------------------------------------------
createClubEvent           ->  POST            /event                     {createEvent}
createClubPage            ->  POST            /club                      {createClub}
deleteClubPage            ->  DELETE          /club/:clubid              {deleteClub}
deleteClubEvent           ->  DELETE          /event/:eventid            {delteEvent}
retrieveAttendees         ->  GET             /event/:eventid/attendees  {getEventAttendees}
retrieveClubMembers       ->  GET             /club/:clubid/members      {getClubMembers}
retrieveClubDetails       ->  GET             /club/:clubid              {getClub}
retrieveDSUser            ->  GET             /user/:userid              {getUser}
retrieveEventDetails      ->  GET             /event/:eventid            {getEvent}
retrieveEventsFeed        ->  GET             /event                     {getAllEvents}
retrieveClubs             ->  GET             /club                      {getAllClubs}
signUp                    ->  POST            /user                      {createUser}
updateAttendingEvent      ->  PUT             /user/events/:eventid      {updateUserEvents}
updateSubscriptionToClub  ->  PUT             /user/clubs/:clubid        {updateUserClubs}
updateUserImage           ->  PUT             /user/:userid/image        {updateUserImage}
updateUserInfo            ->  PUT             /user/:userid              {updateUser}
???                       ->  POST            /event/:eventid/notify     {notifyEventAttendees}
```

**Comment by GRA0007** [comment]
With `updateUserEvents`, are we storing the event attendance on the event object or the user object? I feel like storing it on the event would be more efficient; maybe we should use `PUT /event/:eventid/attendees` instead?

**Comment by GRA0007** [comment]
Oh, and with `updateUserClubs`, I think with a `PUT` request we should be sending the `:clubid` as a query parameter, not in the url

**Comment by giraugh** [comment]
I think we are currently storying it on the user. The event would prob be more efficient though we do have to do both operations at different times. One strategy would be to setup 

> With `updateUserEvents`, are we storing the event attendance on the event object or the user object? I feel like storing it on the event would be more efficient; maybe we should use `PUT /event/:eventid/attendees` instead?

We are currently storing it on the user, though the event may make sense. We do have to do both queries though as we also get a list of events being attended / ever attended by a given user. The API of course doesn't have to directly match the actual DS structure though. Perhaps we could keep it as now on the Datastore, but update the API and then create a DS index on google's end to join the tables for faster queries?

**Comment by GRA0007** [comment]
Yeah sure, I think it makes more sense for the api to `PUT` on `/event/:eventid/attendees` since that's where they are `GET`ed from as well

**Comment by giraugh** [comment]
Yeah, that makes sense. I guess we could do the same with club members?

**Comment by GRA0007** [comment]
Yes good idea

**Comment by giraugh** [comment]
Okay 👍 
I updated my last big mesage w/ that

**Comment by GRA0007** [comment]
I'm also thinking instead of the `/user/:userid/image` route, we can just have `PATCH /user/:userid` accept everything to do with a profile, and it will only patch the fields that are supplied. This will replace the PUT on that route

**Comment by GRA0007** [comment]
Gonna leave this todo list here so I can refer to it and update it:

[] Add editClub route
[] Add route to get user events
[] Add auth to routes (401)
[] Add user checking to routes (403)
[] Verify all routes and return objects

### Routes to verify
[] `GET /event`
[] `POST /event`
[] `GET /event/:eventid`
[] `PATCH /event/:eventid`
[] `DELETE /event/:eventid`
[] `GET /event/:eventid/attendees`
[] `PUT /event/:eventid/attendees`
[] `GET /club`
[] `POST /club`
[] `GET /club/:clubid`
[] `PATCH /club/:clubid`
[] `DELETE /club/:clubid`
[] `GET /club/:clubid/members`
[] `PUT /club/:clubid/members`
[] `GET /user`
[] `POST /user`
[] `GET /user/:userid`
[] `PATCH /user/:userid`
