### ISSUE TITLE
De-typescript the backend 😢

### ISSUE THREAD

**Issue by GRA0007** [csitsociety/stevent#120]
Yeah, maybe ts was a mistake

looks like express was not made for this

we tried :)

**Comment by Ry-DS** [comment]
Typescript over JS is never a mistake! If you need help sorting out types for the backend let me know :)

**Comment by giraugh** [comment]
Oh haha thank you for the offer. We have determined that JS is just a better fit for our project and team given our prior experience. TS is definetely awesome though :D
