### ISSUE TITLE
Write up a privacy policy

### ISSUE THREAD

**Issue by GRA0007** [csitsociety/stevent#65]
We need a privacy policy that addresses information Stevent collects from users, and notes that users under 13 are not allowed on the platform.

**Comment by giraugh** [comment]
Hey @BenKoder, can you write us up a privacy policy with your excellent legalise skills?

**Comment by GRA0007** [comment]
Some ideas you can use as templates:
- https://playpokpok.com/privacy (ignore the region-specific sections)
- https://crab.fit/privacy (this is more relevant for the child policy, we don't want anyone under 13 using the site)
- https://edstem.org/us/privacy (this one is pretty similar to what we want)

**Comment by GRA0007** [comment]
I'm going to put this into a /privacy page
