### ISSUE TITLE
Add a checkbox to the signup for ensuring users are over 13 years of age

### ISSUE THREAD

**Issue by GRA0007** [csitsociety/stevent#66]
A checkbox on the signup page that reads: `I confirm I am over 13 years old and I have read the privacy policy` (linked to `/privacy`).
This will need to be checked on the backend as well otherwise an error is returned.

**Comment by giraugh** [comment]
Prob wait for #44 on this one.

**Comment by giraugh** [comment]
Happy to implement this unless you already have a start @LinusKay?

**Comment by LinusKay** [comment]
Have only taken some time getting comfortable with it, nothing serious. Especially since its a priority task, please go ahead if you would like to take care of it @giraugh

**Comment by giraugh** [comment]
> I'm 13 and ~~this is deep~~ I've read the privacy policy.

 Working on this now.

**Comment by GRA0007** [comment]
over 13, oVER 13!

**Comment by giraugh** [comment]
> over 13, oVER 13!

sry yes ofc
