### ISSUE TITLE
Update user forms to have an `autocomplete` property

### ISSUE THREAD

**Issue by giraugh** [csitsociety/stevent#7]
For example, the login field should have a `autofill="email"` html attribute set so that google autofills it with an email and not a username.

**Comment by poly4concept** [comment]
Hi, @giraugh  I'll love to contribute, will you assign this to me?

**Comment by giraugh** [comment]
> Hi, @giraugh I'll love to contribute, will you assign this to me?

Hi @poly4concept, thank you for the offer. Currently we are just pushing to get this project finalised ahead of our semester 2 at RMIT but once we have that done we will be working more with the community on PRs. I'll let you know once we start on that if you'd like? Thank you again for offering to help out on Stevent.
