### ISSUE TITLE
Prevent `updateAttendingEvent` route in backend from adding multiples of the same event if "I'm going" clicked more than once

### ISSUE THREAD

**Issue by GRA0007** [csitsociety/stevent#93]
Currently, if you click "I'm going" on an event more than once, it will add a duplicate of the same event to your profile. The backend route should check if this event is already in your attending array before adding.

**Comment by giraugh** [comment]
We were having struggles with this the other day. Previously it just didn't even update XD. @Prydeton those fixes got properly merged right?
